ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 8089
    host: 0.0.0.0
jwt:
  domain: "http://192.168.210.221:8080"
  audience: "users"
  realm: "ktor sample app"
  issuer: "http://192.168.210.221:8080"
  secret : "adshjdshjsd"
